image_params:
    img_height: 288
    img_width: 512
    orig_img_width: 512
    orig_img_height: 288
    channels: 1
    n_labels: 3
    max_num_points: 4096
    max_columns: 70
train_params:
    n_labels: 1
    batch_size: 5
    learning_rate: 0.00005
    decay: 0.01
    weights:
        horizon: 1.0
        host_yaw_at_100m: 0.0
        scene_class: 0.0
        scene_class_weights: [0.2, 0.4, 0.4]
    steps_per_epoch: 1111
    max_iter: 1280
    init_filters_num: 8
